### FIND ALL
GET http://localhost:3000/api/v2/pokemon

### FIND ONE
GET http://localhost:3000/api/v2/pokemon/1

### CREATE
POST http://localhost:3000/api/v2/pokemon
Content-Type: application/json

{
  "name": "Bulbasaur",
  "no": 1
}

### UPDATE
PATCH http://localhost:3000/api/v2/pokemon/1
Content-Type: application/json

{

}

### DELETE
DELETE http://localhost:3000/api/v2/pokemon/1
