### FIND ALL
GET http://localhost:3000/api/v2/pokemon

### FIND ONE
GET http://localhost:3000/api/v2/pokemon/642312eed6d7b3435effbdfd

### CREATE
POST http://localhost:3000/api/v2/pokemon
Content-Type: application/json

{
  "name": "garbabge 3",
  "no": 103
}

### UPDATE
PATCH http://localhost:3000/api/v2/pokemon/64232e18ab9ebbf45f36e1c9
Content-Type: application/json

{
  "name": "bulbasaur"
}

### DELETE
DELETE http://localhost:3000/api/v2/pokemon/64233da6870c2cbcec229af8